sudo: false
language: node_js
node_js:
  - "stable"
  - 6
  - 4
  - "0.10"

cache: yarn

env:
  global:
    COVERALLS_PARALLEL: true

after_success: "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
